set(_CATKIN_CURRENT_PACKAGE "hsvthreshold_ros")
set(hsvthreshold_ros_VERSION "0.0.0")
set(hsvthreshold_ros_MAINTAINER "Kritwish Mondal <kritwishm2@gmail.com>")
set(hsvthreshold_ros_PACKAGE_FORMAT "1")
set(hsvthreshold_ros_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(hsvthreshold_ros_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(hsvthreshold_ros_BUILDTOOL_DEPENDS "catkin")
set(hsvthreshold_ros_BUILDTOOL_EXPORT_DEPENDS )
set(hsvthreshold_ros_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(hsvthreshold_ros_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(hsvthreshold_ros_TEST_DEPENDS )
set(hsvthreshold_ros_DOC_DEPENDS )
set(hsvthreshold_ros_DEPRECATED "")